- name: Update apt cache
  apt:
    update_cache: yes
    force_apt_get: yes

- name: Install dependencies
  apt:
    name:
      - docker.io
      - awscli
      - curl
      - unzip
    state: present

- name: Install Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/latest/download/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: '0755'
