- name: Ensure GitHub CLI is installed
  shell: |
    if ! command -v gh &> /dev/null; then
      curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
      sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list
      sudo apt update && sudo apt install gh -y
    fi
  args:
    executable: /bin/bash
  changed_when: false

- name: Authenticate GitHub CLI
  shell: |
    echo "{{ github_token }}" | gh auth login --with-token --hostname github.com
  args:
    executable: /bin/bash
  environment:
    GITHUB_TOKEN: "{{ github_token }}"
  no_log: true  #Hide sensitive token from logs
  register: gh_auth_output
  changed_when: false

- name: Set GitHub secrets
  shell: |
    gh secret set {{ item.name }} --repo "{{ github_repo }}" --body "{{ item.value }}"
  args:
    executable: /bin/bash
  with_items:
    - { name: "JENKINS_URL", value: "{{ jenkins_url }}" }
    - { name: "JENKINS_USER", value: "{{ jenkins_user }}" }
    - { name: "JENKINS_API_TOKEN", value: "{{ jenkins_api_token }}" }
    - { name: "JENKINS_PIPELINE", value: "{{ jenkins_pipeline }}" }
  no_log: true  #Prevent secrets from leaking
