
- name: Ensure GitHub CLI is installed
  ansible.builtin.shell: |
    if ! command -v gh &> /dev/null; then
      curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
      sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list
      sudo apt update && sudo apt install gh -y
    fi
  args:
    executable: /bin/bash

- name: Authenticate GitHub CLI
  ansible.builtin.shell: |
    echo "{{ github_token }}" | gh auth login --with-token --hostname github.com
  environment:
    GITHUB_TOKEN: "{{ github_token }}"
  args:
    executable: /bin/bash

- name: Set GitHub secret for JENKINS_URL
  ansible.builtin.shell: |
    gh secret set JENKINS_URL --repo "{{ github_repo }}" --body "{{ jenkins_url }}"
  args:
    executable: /bin/bash

- name: Set GitHub secret for JENKINS_USER
  ansible.builtin.shell: |
    gh secret set JENKINS_USER --repo "{{ github_repo }}" --body "{{ jenkins_user }}"
  args:
    executable: /bin/bash

- name: Set GitHub secret for JENKINS_API_TOKEN
  ansible.builtin.shell: |
    gh secret set JENKINS_API_TOKEN --repo "{{ github_repo }}" --body "{{ jenkins_api_token }}"
  args:
    executable: /bin/bash

- name: Set GitHub secret for JENKINS_PIPELINE
  ansible.builtin.shell: |
    gh secret set JENKINS_PIPELINE --repo "{{ github_repo }}" --body "{{ jenkins_pipeline }}"
  args:
    executable: /bin/bash
