- name: Install Docker credential helper prerequisites
  apt:
    name:
      - gnupg2
      - pass
    state: present
    update_cache: true
  become: true

- name: Ensure GPG config directory exists
  file:
    path: "{{ gpg_home }}"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0700'
  become: true

- name: Create GPG batch config file
  copy:
    dest: "{{ gpg_key_config_path }}"
    content: |
      %no-protection
      Key-Type: RSA
      Key-Length: 2048
      Subkey-Type: RSA
      Subkey-Length: 2048
      Name-Real: {{ gpg_key_name }}
      Expire-Date: 0
      %commit
    owner: ubuntu
    group: ubuntu
    mode: '0600'
  become: true

- name: Generate GPG key (if not exists)
  shell: |
    gpg --batch --gen-key {{ gpg_key_config_path }}
  args:
    creates: "{{ gpg_home }}/pubring.kbx"
  become: true
  become_user: "{{ ansible_user }}"

- name: Get GPG key ID for {{ gpg_key_name }}
  shell: |
    gpg --list-keys --with-colons {{ gpg_key_name }} | awk -F: '/^pub/ { print $5 }'
  register: gpg_key_id
  changed_when: false
  become: true
  become_user: "{{ ansible_user }}"

- name: Initialize pass with GPG key
  shell: |
    pass init "{{ gpg_key_id.stdout }}"
  args:
    creates: "{{ pass_store }}"
  become: true
  become_user: "{{ ansible_user }}"

- name: Ensure ~/.docker directory exists
  file:
    path: "/home/{{ ansible_user }}/.docker"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0700'
  become: true

- name: Configure Docker to use pass as credential store
  copy:
    dest: "/home/{{ ansible_user }}/.docker/config.json"
    content: |
      {
        "credsStore": "pass"
      }
    mode: '0600'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: true